# Generated by Django 2.0.6 on 2018-06-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='images')),
                ('image_desc', models.CharField(max_length=100)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog_files',
            },
        ),
    ]
